apiVersion: v1
kind: Pod
metadata:
  name: ryan-flask-pod-a
  labels:
    app: ryan-flask-pod-a
spec:
  containers:
  - name: ryan 
    image: ryanckhung/ryanflask
    ports:
    - containerPort: 5000
