apiVersion: v1
kind: Pod
metadata:
  name: ryan-b
spec:
  containers:
  - name: ryan-container
    image: ryanckhung/ryantest
    volumeMounts:
    - mountPath: /log
      name: log-volume

  volumes:
  - name: log-volume
    persistentVolumeClaim:
      claimName: pvc-1
