apiVersion: v1
kind: Pod
metadata:
  name: ryan
spec:
  containers:
  - image: ryanckhung/ryantest
    name: ryan-container
    volumeMounts:
    - mountPath: /usr/src/app/data/
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /home/ryanhung/Desktop/temp_folder
      type: Directory
